# Dismiss screensaver on any keyboard or mouse input
ANY_UNICODE quit
SPACE quit
ENTER quit
ESC quit
BS quit
DEL quit
TAB quit
UP quit
DOWN quit
LEFT quit
RIGHT quit
PGUP quit
PGDWN quit
HOME quit
END quit
MOUSE_MOVE quit
MOUSE_BTN0 quit
MOUSE_BTN1 quit
MOUSE_BTN2 quit
MOUSE_BTN3 quit
MOUSE_BTN4 quit
MOUSE_BTN5 quit
MOUSE_BTN6 quit
AXIS_UP quit
AXIS_DOWN quit
AXIS_LEFT quit
AXIS_RIGHT quit
